name: Pylint

on:
  push:
    branch: main
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/pytest.yml"


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run black
      run: black .
