name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run the tests
        run: pytest tests/